//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace NorthWind.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel;

    [MetadataType(typeof(MetaCustomers))]

    public partial class Customers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Customers()
        {
            this.Orders = new HashSet<Orders>();
        }

        [DisplayName("顧客編號")]
        [Required(ErrorMessage = "顧客編號為必填")]
        [RegularExpression("[A-Z]{5}", ErrorMessage = "格式有誤")]
        public string CustomerID { get; set; }

        [DisplayName("公司名稱")]
        [Required(ErrorMessage = "公司名稱為必填")]
        [StringLength(40, ErrorMessage = "公司名稱最多40字")]
        public string CompanyName { get; set; }

        [DisplayName("聯絡人姓名")]
        [StringLength(30, ErrorMessage = "聯絡人姓名最多30字")]
        public string ContactName { get; set; }

        [DisplayName("聯絡人職稱")]
        [StringLength(30, ErrorMessage = "聯絡人職稱最多30字")]
        public string ContactTitle { get; set; }

        [DisplayName("地址")]
        [StringLength(60, ErrorMessage = "地址最多60字")]
        public string Address { get; set; }

        [DisplayName("城市")]
        [StringLength(15, ErrorMessage = "城市最多15字")]
        public string City { get; set; }

        [DisplayName("區域")]
        [StringLength(15, ErrorMessage = "區域最多15字")]
        public string Region { get; set; }

        [DisplayName("郵遞區號")]
        [StringLength(10, ErrorMessage = "郵遞區號最多10字")]
        public string PostalCode { get; set; }

        [DisplayName("國家")]
        [StringLength(15, ErrorMessage = "國家最多15字")]
        public string Country { get; set; }

        [DisplayName("連絡電話")]
        [Required(ErrorMessage = "連絡電話為必填")]
        [StringLength(24, ErrorMessage = "連絡電話最多24字")]
        public string Phone { get; set; }

        [DisplayName("傳真號碼")]
        [StringLength(24, ErrorMessage = "傳真號碼最多24字")]
        public string Fax { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Orders> Orders { get; set; }
    }
}
